#
# Module manifest for module 'ChocolateyUpdateMonitor'
#
# Generated by: Dailen Gunter
#
# Generated on: 7/25/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ChocolateyUpdateMonitor.psm1'

# Version number of this module.
ModuleVersion = '0.1.3'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'e753b6cb-37e8-4a76-adb3-a6e3f0cbad95'

# Author of this module
Author = 'Dailen Gunter'

# Company or vendor of this module
CompanyName = 'WideData'

# Copyright statement for this module
Copyright = 'WideData Corporation, Inc.'

# Description of the functionality provided by this module
Description = 'This module monitors for outdated Chocolatey packages and has a built in function to create a scheduled task that cachesa list of pending updates to make installation of them faster. It caches the update list to a JSON file, has preferences for which repos to check and install updates from, and can be used just to output the contents of the update information. Rocolatey support is also integrated. If it is present it will try to use it by default but you can set the preferences to not use it if you prefer.'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    "Get-ChocoMonitorConfig",
    "Get-ChocolateyUpdate",
    "Show-ChocolateyUpdate",
    "Install-ChocolateyUpdate",
    "Register-ChocoMonitorTask",
    "Set-ChocoMonitorConfig",
    "Unregister-ChocoMonitorTask"
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("package","management","roco","rocolatey","chocolatey","choco","deployment","widedata")

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/widedata/scripts/tree/main/modules/ChocolateyUpdateMonitor'

        # A URL to an icon representing this module.
        IconUri = 'https://wdc.help/icons/Box.Packed.png'

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

